### ISSUE TITLE
Add support for deno.jsonc 

### ISSUE THREAD

**Issue by nberlette** [deco-cx/deno-githooks#1]
The `deno.jsonc` is used by many projects in the Deno community, and is mentioned as a [supported extension in the Deno Manual](https://deno.land/manual@v1.26.2/getting_started/configuration_file). 

Unfortunately, this module's current API assumes all project will be using `deno.json`, rendering it effectively useless for anything else. Deno's Standard Library [has a nice JSONC module](https://deno.land/std/encoding/jsonc.ts?source), that could help make this a pretty simple fix.

If I can fit it in my schedule I'll put together a quick PR to fix this issue.

Thanks!

**Comment by tuhanayim** [comment]
This one looks like abandoned for now. You can check my fork here: https://github.com/tuhanayim/denoh
