### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by boywithkeyboard** [deco-cx/deno-githooks#3]
Is this project still maintained?

**Comment by boywithkeyboard** [comment]
cc: @igorbrasileiro

**Comment by igorbrasileiro** [comment]
Yeah, @boywithkeyboard. Cc @guifromrio

**Comment by boywithkeyboard** [comment]
@igorbrasileiro Can I apply as a core maintainer of this library? I have a few ideas to improve this library (all backwards compatible).

I already maintain a few other Deno libraries, such as [cheetah](https://github.com/azurystudio/cheetah), [byte](https://github.com/azurystudio/byte), and [authenticus](https://github.com/azurystudio/authenticus).

**Comment by igorbrasileiro** [comment]
Yes sure

**Comment by boywithkeyboard** [comment]
@igorbrasileiro ok so what do I need to do to get the Maintainer role?

**Comment by boywithkeyboard** [comment]
@guifromrio what do you think?

**Comment by guifromrio** [comment]
@boywithkeyboard sorry for the delay! Was just checking your other libraries, loved them all. Just sent you an invite!

BTW, we are working on a next-wordpress type of framework here, I would love to schedule a call and show you our "deno composable" framework: https://github.com/deco-cx/deco

Would you be interested?

**Comment by boywithkeyboard** [comment]
@guifromrio sure! Just send me a friend request on Discord (same username) or send me an email (me@samuelkopp.de) :)

**Comment by boywithkeyboard** [comment]
--- deleted my comment for privacy ---
